# Generated by Django 2.1.3 on 2018-11-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Girl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField()),
                ('desc', models.DateField()),
                ('published', models.DateTimeField()),
                ('source', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=100)),
                ('used', models.BooleanField(default=True)),
            ],
        ),
    ]
