# Generated by Django 2.1.3 on 2018-11-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view01', '0002_girl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='girl',
            name='created_date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='girl',
            name='desc',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='girl',
            name='published',
            field=models.CharField(max_length=255),
        ),
    ]
